version: "3.8"

volumes:
  nextcloud_data:
  db_data:

networks:
  ncnet:
    driver: overlay

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=changeme-root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=changeme
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ncnet
    deploy:
      placement:
        constraints:
          - node.hostname == vm-w-01
      restart_policy:
        condition: any

  app:
    image: nextcloud:stable
    environment:
      - TZ=Europe/Paris
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=changeme
      - NEXTCLOUD_TRUSTED_DOMAINS=10.0.11.11
      # (optionnel) pré-config auto de l'admin au premier démarrage :
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=adminpass
    volumes:
      - nextcloud_data:/var/www/html
    ports:
      - "8080:80"       # => http://10.0.11.11:8080
    networks:
      - ncnet
    deploy:
      placement:
        constraints:
          - node.hostname == vm-w-01
      restart_policy:
        condition: any
