networks:
  nc_net:
    driver: overlay                                 # Overlay network for Nextcloud
    attachable: true                                # Allows standalone containers to connect to this network

volumes:
  nc_nextcloud_data: {}                             # Volume for Nextcloud data
  nc_db_data: {}                                    # Volume for database data

configs:
  php_ini:
    file: ../services/php/php.ini                   # Configuration file for PHP

secrets:
  nc_db_password:
    file: ../secrets/nc_db_password.txt             # Secret for database password
  nc_db_root_password:
    file: ../secrets/nc_db_root_password.txt        # Secret for database root password

services:
  
  nc_redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks: [nc_net]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.apps == true

  nc_mariadb:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: run/secrets/nc_db_password
      MYSQL_ROOT_PASSWORD_FILE: run/secrets/nc_db_root_password
    secrets:
      - nc_db_password
      - nc_db_root_password
    volumes:
      - nc_db_data:/var/lib/mysql
    networks: [nc_net]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: any
        deley: 5s
        max_attempts: 0
      placement:
        constraints:
          - node.labels.apps == true

  nextcloud:
    image: nextcloud:29-apache
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/nc_db_password
      MYSQL_HOST: ${MYSQL_HOST}

      REDIS_HOST: nc-redis
      REDIS_HOST_PORT: 6379

      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      PHP_MEMORY_LIMIT: 512M
    configs:
      - source: php_ini
        target: /usr/local/etc/php/conf.d/zzz-custom.ini
    secrets:
      - nc_db_password
    volumes:
      - nc_nextcloud_data:/var/www/html
    networks: [nc_net]
    ports:
      - "${PUBLISHED_PORT}:80"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -fs http://localhost/status.php || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.apps == true